travis:
  secure:
    BINSTAR_TOKEN: HQCCqkAwrogCDuNUnj5CWog2WnLqhwlWP7DC7uxkRrar+FjRer4Ah2D5ly+HDEE/0tEZ9zrWBwZf1uavPfW5OCA8i+Xdp7lCIJrIchxPtaSvdKxHFXHY3OIQWlY8r8SZVhCN0tBzk8vNzYmlLa6KOxPTGq25LYET0hNpci1FAC8VaY02hUNzmbjx9VIEXppbQ9taF/3gFSaUvAMG/QZexsS5pL+jABeUsdq7i5fQ9oVyaE3dXRSB5tfc45VACavZ9063dwPls8bLppLY7d5l649bfVN6e4khMuMt9ZOvX6J+Q6067oh9banhj5zSvZ77ewW2AN44dNtA++OvEaONKJBJ+J1xKpOYDUbO/CQsalqoFa9dT1DH2RIfVAX8JWlwymc8bBYLInUX1RYBrgZOttTDmizIdU976ltgoPc+WO8pWaDQAFISOyr/1iGt6yeS2ETr0v0MEaSexSxMAeglOrrWgSfFJt6Zbr1xfhC5TdFb8JrYTEl7YF9xNVnR1w9CoLQKqUl/NC5IGOOUplNoz0imrCANJknrbf/9U9A85Ck7L1EYoS1fkUNbZXn20mnVnadW5POJNyd1r6rPZCSR1bwFDD7LDtj5NqsApINvCbQHv8BuUvZ1hLk0usVIVW0fZbNo0rYY5Ma/PSuX1R5dIImnIfKRqJE6prigZ6UMr3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
